---
abstract: 'Parse SCO files (PIFs)'
author:
  - 'osfameron, C<< <osfameron at cpan.org> >>'
  - 'OSFAMERON <osfameron@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::LongString: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-SCORM
no_index:
  directory:
    - inc
    - t
requires:
  Any::Moose: 0
  File::Temp: 0
  IPC::Run: 0
  JSON::Any: 0
  Mouse: 0
  Mouse::Util::TypeConstraints: 0
  MouseX::AttributeHelpers: 0
  Params::Coerce: 0
  Scalar::Util: 0
  XML::Twig: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.06
